export const LocationEnum = [
  "sreemangal",
  "bagerhat",
  "dhaka",
  "bandarban",
  "barguna",
  "barishal",
  "bhola",
  "bogra",
  "brahmanbaria",
  "chandpur",
  "chapainawabganj",
  "chattogram",
  "chuadanga",
  "comilla",
  "cox bazar",
  "dinajpur",
  "faridpur",
  "feni",
  "gaibandha",
  "gazipur",
  "gopalganj",
  "habiganj",
  "jamalpur",
  "jashore",
  "jhalokati",
  "jhenaidah",
  "joypurhat",
  "khagrachari",
  "khulna",
  "kishoreganj",
  "kushtia",
  "kushtia",
  "lakshmipur",
  "lalmonirhat",
  "madaripur",
  "magura",
  "manikganj",
  "meherpur",
  "munshiganj",
  "mymensingh",
  "naogaon",
  "narail",
  "narayanganj",
  "narsingdi",
  "natore",
  "nawabganj",
  "netrakona",
  "nilphamari",
  "noakhali",
  "pabna",
  "gazipur",
  "pairozpur",
  "patuakhali",
  "pirojpur",
  "rajbari",
  "rajshahi",
  "rangamati",
  "rangpur",
  "satkhira",
  "shariatpur",
  "sherpur",
  "sirajganj",
  "sunamganj",
  "sylhet",
  "tangail",
  "thakurgaon",
];

export const servicecategoryEnum = [
  "hotels",
  "apartments",
  "resorts",
  "villas",
];

export const facilitesEnum = [
  "freeze",
  "wifi",
  "free drinks",
  "swiming pull",
  "24-hour front desk",
  "Free parking",
  "Room service",
];
export const roomsCategoryEnum = ["delux", "delux king", "delux twin", "3 bed"];
